spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydb}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  data:                          # ← 'data' ke andar daalo
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: 6379

server:
  port: 8080